### ISSUE TITLE
Improvements and patches for zetaback

### ISSUE THREAD

**Issue by jgmills** [omniti-labs/zetaback#4]
I've been installing zetaback on my home network.  In the process, I've come across several errors and omissions.  The first is that `make install' repeats the steps that have already been done by`make'.  This is a problem if the commands are run by different users.  This is caused by missing dependancies in the Makefile.  My patch Makefile.in.diff corrects this problem.

Another problem I encountered with the zetaback server is that locking failed with no message.  My patch zetaback.in.diff corrects this problem and several others.  Zetaback now prints:

```
Cannot open: /dpool/unix/amd/.list
```

in this case.  Another is that zetaback always prints:

```
Using custom ssh config file
```

even if it's not doing that.  Finally, zetaback only reports the wait status of failed remote commands.  My patch adds three separate `die' messages to indicate different reasons for the failure.

I discovered that I needed to escape slashes in zetaback_agent.conf patterns.  This requirement should either be fixed or documented in the man page.  I also discovered that there was no way to quote values in zetaback.conf .  I needed this ability to enter commands that contained spaces.  Again, this bug should either be fixed or documented in the man page.

Did I miss finding another document?  We really need one to describe the setup required on the zetaback server and the agent hosts before using zetaback.  The setup entails at least six steps, some of which may be new to backup administrators.  We also need one to show how to put zetaback into production, and how to do restores when they are required.

**Comment by mamurphy** [comment]
If you would like to submit a pull request with your patches, I would be happy to take a look and merge them.

Unfortunately the only other documentation we currently have is https://labs.omniti.com/labs/zetaback.

**Comment by jgmills** [comment]
On Wed, Sep 14, 2016 at 08:59:44AM -0700, Marissa wrote:
>    If you would like to submit a pull request with your patches, I would
>    be happy to take a look and merge them.

I'm not sure how to do that, or even what it means.  Could you give me
a bit more information?

>    Unfortunately the only other documentation we currently have is
>    [1]https://labs.omniti.com/labs/zetaback.

That essentially describes what it is, what it requires, and how to
install it.  It's missing details on how to set it up, and how to use
it.

-- 
-Gary Mills-		-refurb-		-Winnipeg, Manitoba, Canada-

**Comment by mamurphy** [comment]
You referred to patches you had written in your original post to this issue, but I cannot see those files. You should submit a pull request so that I can check them out and test them before merging them into the master branch. For more information about pull requests please see https://help.github.com/articles/creating-a-pull-request/

**Comment by jgmills** [comment]
On Thu, Sep 15, 2016 at 01:01:04PM -0700, Marissa wrote:
>    You referred to patches you had written in your original post to this
>    issue, but I cannot see those files.

I can't see them either, although I did submit them.

>    You should submit a pull request
>    so that I can check them out and test them before merging them into the
>    master branch. For more information about pull requests please see
>    [1]https://help.github.com/articles/creating-a-pull-request/

I can't seem to get started.  That article tells me to select the
branch in which I've made changes.  I haven't made any changes.  The
only branch I see is the master branch.

-- 
-Gary Mills-		-refurb-		-Winnipeg, Manitoba, Canada-

**Comment by postwait** [comment]
this tutorial might help.  Just use the zetaback repo as a substitute for the repo they discuss.

https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR

**Comment by jgmills** [comment]
On Fri, Sep 16, 2016 at 08:12:55AM -0700, Theo Schlossnagle wrote:
>    this tutorial might help. Just use the zetaback repo as a substitute
>    for the repo they discuss.
> 
>    [1]https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to
>    -Submit-Your-First-PR

Thanks.  That got me further along.  Now when I try the clone on my
local computer, I get:

    Cloning into zetaback...
    Permission denied (publickey).
    fatal: The remote end hung up unexpectedly

I assume this means I have to add my public key to my github account.
So, I click on my profile picture on github and then `Edit Profile', I
see `SSH and GPG keys'.  When I click on it, it says:

    There are no SSH keys with access to your account.

When I click on `New SSH key', nothing happens.  What do I do now?

-- 
-Gary Mills-		-refurb-		-Winnipeg, Manitoba, Canada-

**Comment by postwait** [comment]
You could use https cloning.

Or figure out how to add your ssh public key.

**Comment by jgmills** [comment]
On Fri, Sep 16, 2016 at 11:37:50AM -0700, Theo Schlossnagle wrote:
>    You could use https cloning.
>    Or figure out how to add your ssh public key.

The second choice worked.  I had been using Solaris 11.3 with Firefox
20.0.1 .  To add the public key, I switched to a Linux box running a
later version of Firefox.  There, I got more items in the the Profile
Picture menu, and `New SSH key' brought up a window where I could
enter my public key.  After that, `git clone' worked on my illumos
machine.

I don't know what went wrong, but I suspect I can complete the pull
request now.

-- 
-Gary Mills-		-refurb-		-Winnipeg, Manitoba, Canada-

**Comment by jgmills** [comment]
On Wed, Sep 14, 2016 at 08:59:44AM -0700, Marissa wrote:
>    If you would like to submit a pull request with your patches, I would
>    be happy to take a look and merge them.

Thanks to you and Theo, my pull request has finally been successful.
I trust this is what you needed.

PS: Github is very confusing when some buttons are missing and others
are present but don't function.

-- 
-Gary Mills-		-refurb-		-Winnipeg, Manitoba, Canada-
