### ISSUE TITLE
[SOLVED] can't do dataset backup

### ISSUE THREAD

**Issue by syswipe** [omniti-labs/zetaback#7]
Hi!
can anybody explain me how to execute issues with dataset backup?
it was some network outages with my backup server, so i have no backups for since 4 march.
I try to run zetaback backup manually, but i received the next error:

```
backup@backup-tst:~$ /opt/omni/zetaback/bin/zetaback -ff -b -d -h nfs1.prod.local
Planning 'nfs1.prod.local'
Acquiring lock for nfs1.prod.local:.list
 => Filesystems for nfs1.prod.local (zetaback_agent -l output)
    data/nfs/crm-site.int [__zb_full_1486615036,__zb_incr,__zb_dset_1490710525,__zb_dset_1490710576,__zb_dset_1490710685]
=> No/default class
 => Scanning '/data/nfs/crm-site.int' for old backups of 'data/nfs/crm-site.int'.
 => doing dataset backup
Acquiring lock for nfs1.prod.local:ZGF0YS9uZnMva2V5c3VydmV5LmNvbQ==
Releasing lock for nfs1.prod.local:.list
Using custom ssh config file: -F /opt/omni/zetaback/etc/ssh_config
Receiving to zfs filesystem data/nfs/crm-site.int/ZGF0YS9uZnMva2V5c3VydmV5LmNvbQ--@1490710755
   => ssh -F /opt/omni/zetaback/etc/ssh_config nfs1.prod.local sudo /opt/omni/zetaback/bin/zetaback_agent -z data/nfs/crm-site.int -i 1488603602 -s 1490710755
 => failure zfs_do_backup nfs1.prod.local:data/nfs/crm-site.int s: error: 256 at /opt/omni/zetaback/bin/zetaback line 808. at /opt/omni/zetaback/bin/zetaback line 843.
Releasing lock for nfs1.prod.local:ZGF0YS9uZnMva2V5c3VydmV5LmNvbQ==
Releasing lock for nfs1.prod.local:.list
Acquiring lock for nfs1.prod.local:.list
 => Filesystems for nfs1.prod.local (zetaback_agent -l output)
    data/nfs/crm-site.int [__zb_full_1486615036,__zb_incr,__zb_dset_1490710525,__zb_dset_1490710576,__zb_dset_1490710685,__zb_dset_1490710755]
Releasing lock for nfs1.prod.local:.list
```

**Comment by nshalman** [comment]
https://github.com/omniti-labs/zetaback/blob/master/zetaback.in#L808
Something is going wrong somewhere in the SSH command of:
`ssh -F /opt/omni/zetaback/etc/ssh_config nfs1.prod.local sudo /opt/omni/zetaback/bin/zetaback_agent -z data/nfs/crm-site.int -i 1488603602 -s 1490710755`

The problem is either in the SSH connection itself, or in the `nfs1.prod.local` machine's ability to invoke the `zetaback_agent`

I would try running the following command to see that SSH is still working and `sudo` is able to run `zetaback_agent`:
`ssh -F /opt/omni/zetaback/etc/ssh_config nfs1.prod.local sudo /opt/omni/zetaback/bin/zetaback_agent -v`

**Comment by syswipe** [comment]
well, i checked ssh connection - all is ok. i fixed problem by removing target dataset on backup server and recreate backup.
but tomorrow i rebooted server for maintenance proposes and zetaback backup failed again: 

failure zfs_do_backup nfs1.prod.local:data/nfs/crm-site.int s: dump failed (received snapshot data/nfs/keysurvey.com/ZGF0YS9uZnMva2V5c3VydmV5LmNvbQ--@1491563627 does not exist

**Comment by nshalman** [comment]
Are there cron jobs or other things that are creating and destroying snapshots outside of zetaback on either the `backup-tst` or the `nfs1.prod.local` machine? zetaback makes certain assumptions about ZFS snapshots persisting until it deletes them... Assumptions that from the output you're showing appear to have been violated.

**Comment by syswipe** [comment]
no, i have no additional cronjobs...

**Comment by syswipe** [comment]
problem reproduced. I clear all snapshots on backup server and source host, and recreated whole target filesysem. The first backup was successful, but the next one failed with the same error:

 failure zfs_do_backup nfs1.prod.local :data/nfs/crm-site.int  s: dump failed (received snapshot data/nfs/crm-site.int/ZGF0YS9uZnMva2V5c3VydmV5LmNvbQ--@1491717610 does not exist) at /opt/omni/zetaback/bin/zetaback line 843

any idea? could you explain me what interval should I specify for full_backup & backup_interval for dataset mode?

May be I need some specific permissions for zfs (backups are doing as backup user)

**Comment by mamurphy** [comment]
I _believe_ that zetaback needs to be run as a privileged user at this time. Please try giving sudo access for your backup user to run zetaback and see if that solves your issue.

**Comment by syswipe** [comment]
Problem is solved
well, it is no necessary to run zetaback as root. 
i investigated problem and found solution. it was lack of permission to target zfs filesystem via zfs allow.
for successful dataset backup permission to receive is needed.
